if True:
    if True:
        if True:
            if True:
                if True:
                    if True:
                        if True:
                            if True:
                                if True:
                                    if True:
                                        if True:
                                            if True:
                                                if True:
                                                    if True:
                                                        if True:
                                                            if True:
                                                                if True:
                                                                    if True:
                                                                        if True:
                                                                            if True:
                                                                                if True:
                                                                                    if True:
                                                                                        if True:
                                                                                            if True:
                                                                                                if True:
                                                                                                    if True:
                                                                                                        if True:
                                                                                                            if True:
                                                                                                                if True:
                                                                                                                    if True:
                                                                                                                        if True:
                                                                                                                            if True:
                                                                                                                                if True:
                                                                                                                                    if True:
                                                                                                                                        if True:
                                                                                                                                            if True:
                                                                                                                                                if True:
                                                                                                                                                    if True:
                                                                                                                                                        if True:
                                                                                                                                                            if True:
                                                                                                                                                                if True:
                                                                                                                                                                    if True:
                                                                                                                                                                        print("True!") 